### ISSUE TITLE
Folder Structure

### ISSUE THREAD

**Issue by OverallGod** [mqhirr/Zephyr#5]
What is the folder structure and all the required files needed to run the server. I could dig through all the code, but I figure it would be easier to ask.

**Comment by mqhirr** [comment]
I'll release core soon as I come back from school the next day.

**Comment by OverallGod** [comment]
Okay, I have made a config file using everything the code calls for however I still get failed to parse config.json `{"enable_whitelist":false, "whitelist":[], "http_port":80, "server_port":17198, "server_ip":"127.0.0.1", "use_wuplog":false, "server_name":"Server", "server_discord":"https://discord.gg/SJuVZfdbFB", "debug":false, "server_website":"xfinites.com", "server_email":"jordan@xfinites.com", "creators":["jordan"], "block_proxy":0, "gitbuild":"true"}`

**Comment by OverallGod** [comment]
Simple mistake, ive fixed it

**Comment by mqhirr** [comment]
(Here)[https://www.mediafire.com/file/8jfwl5joildq3y1/Zephyr_Core.zip/file] is the core folder structure with the executable,you may change it since it is perhaps an old exec.
